### ISSUE TITLE
BOM more details?

### ISSUE THREAD

**Issue by ufxela** [RootCNC/Root-3-CNC#1]
- What width should timing belt be?
- number of each type of nut/screw which you used? Though this may be tedious to count up...
- bom uses 2.1 instead of 3 in the electronics section
- Maybe amazon/aliexpress/banggood affiliate links? You can make money from these and I'd be more than happy to support you by purchasing from them :)

**Comment by RootCNC** [comment]
@ufxela 

> What width should timing belt be?

15mm worked well for me - although Root 2 did use 6mm. I'll recommend using the widest you can get both belt and pulleys for.

> number of each type of nut/screw which you used? Though this may be tedious to count up... 


extremely tedious, I did count it but kept getting different answers. I typically buy packs of 50 or 100 as they give a better value. but 6, 10, 16, 20, 25, 30, 35mm are a good start for M3 screws. (I'll look to improve this information)

> BOM uses 2.1 instead of 3 in the electronics section

This needs correcting - R2.1 was the release name for Root 3 

> Maybe amazon/aliexpress/banggood affiliate links? You can make money from these and I'd be more than happy to support you by purchasing from them :)

Defiantly in the works for Root 4 :) (I'm trying to work out Aliexpress's system for affiliate links) I'll look to improve this for all the machines.

hope that help Pete
